// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
using System;
using System.Collections;
using System.Collections.Generic;



	public class Wall
	{
		public Quaternion orintation;
		public Vector3 Wall_position;
		public GameObject Wall_3d;

		public Wall (Quaternion orintation, Vector3 Wall_position, GameObject Wall_3d)
		{
			this.orintation = orintation;
			this.Wall_position = Wall_position;
			this.Wall_3d = Wall_3d;
		}
	}


